project_name: caddy-ingress
version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/caddy
    binary: ingress-controller
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - s390x
    mod_timestamp: "{{ .CommitTimestamp }}"

dockers_v2:
  - images:
      - "{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
      - "ghcr.io/{{ .Env.GITHUB_REPOSITORY_OWNER }}/{{ .ProjectName }}"
    tags:
      - "v{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ else }}latest{{ end }}"
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/s390x
    labels:
      "org.opencontainers.image.description": "Caddy ingress controller for Kubernetes - with Cloudflare support!"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"

release:
  disable: true

checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
