FROM golang:1.27 as build

ENV CGO_ENABLED=0

WORKDIR /go/ingress-controller

COPY go.mod go.sum /go/ingress-controller/
RUN go mod download

COPY . .
RUN go build -o ./bin/ingress-controller ./cmd/caddy

FROM alpine:latest

# added zlib to address CVE-2026-22184
# added openssl to address CVE-2026-2673
# added musl to address CVE-2026-40200
RUN apk update && \
    apk add --no-cache --upgrade \
        zlib \
        openssl \
        musl 

EXPOSE 80 443

COPY --from=build /go/ingress-controller/bin/ingress-controller /ingress-controller

ENTRYPOINT ["/ingress-controller"]