apiVersion: v2
name: caddy-ingress-controller
home: https://github.com/butlergroup/caddy-ingress
description: A Helm chart for the Caddy Kubernetes ingress controller
icon: https://caddyserver.com/resources/images/caddy-circle-lock.svg
type: application
version: 1.5.54
appVersion: "v1.0.3"
keywords:
  - ingress-controller
  - caddyserver
sources:
  - https://github.com/butlergroup/caddy-ingress
maintainers:
  - name: mavimo
    url: https://github.com/mavimo
  - name: embraser01
    url: https://github.com/embraser01
  - name: butlergroup
    url: https://github.com/butlergroup
