# Default values for caddy-ingress-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
# Use to test in minikube context
minikube: false
image:
  registry: docker.io
  repository: davidiven/caddy-ingress
  pullPolicy: IfNotPresent
  tag: "v1.0.5"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
# Default values for the caddy ingress controller.
ingressController:
  watchNamespace: ""
  verbose: false
  rbac:
    create: true
  className: "caddy"
  classNameRequired: false
  leaseId: ""
  env:
    - name: CF_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cloudflare-api-token
          key: CF_API_TOKEN
  config:
    acmeEABKeyId: ""
    acmeEABMacKey: ""
    # -- Acme Server URL
    acmeCA: ""
    acmeDNSProvider: "cloudflare"
    acmeDNSResolvers: ["1.1.1.1"]
    debug: false
    email: ""
    metrics: true
    proxyProtocol: false
    experimentalSmartSort: false
    onDemandTLS: false
    permissionEndpoint: ""
loadBalancer:
  enabled: true
  # Deprecated in Kubernetes v1.24
  loadBalancerIP:
  # Set to 'Local' to maintain the client's IP on inbound connections
  externalTrafficPolicy:
  annotations: {}
  # service.beta.kubernetes.io/aws-load-balancer-type:
  # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type:
  # service.beta.kubernetes.io/aws-load-balancer-scheme:
  # service.beta.kubernetes.io/aws-load-balancer-eip-allocations:
  # service.beta.kubernetes.io/aws-load-balancer-subnets:
  labels: {}
service:
  # Set to 'Local' to maintain the client's IP on inbound connections
  externalTrafficPolicy: Cluster
  # Enable internal traffic policy for the service
  internalTrafficPolicy: Cluster
  annotations: {}
  # service.beta.kubernetes.io/aws-load-balancer-type:
  # service.beta.kubernetes.io/aws-load-balancer-nlb-target-type:
  # service.beta.kubernetes.io/aws-load-balancer-scheme:
  # service.beta.kubernetes.io/aws-load-balancer-eip-allocations:
  # service.beta.kubernetes.io/aws-load-balancer-subnets:
  ## Service type
  type: ClusterIP
  ## IP address for type ClusterIP
  clusterIP: ""
  ipDualStack:
    enabled: false
    ipFamilies: ["IPv6", "IPv4"]
    ipFamilyPolicy: "PreferDualStack"
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "caddy-ingress-controller"
podAnnotations: {}
podSecurityContext: {}
# fsGroup: 2000

podDisruptionBudget:
  minAvailable: 1
  maxUnavailable:
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - SYS_ADMIN
  runAsUser: 1000
  runAsGroup: 1000
  runAsNonRoot: true
resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
